"""empty message

Revision ID: 548b56a0ceca
Revises:
Create Date: 2023-07-26 14:02:29.829043

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "548b56a0ceca"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plugin3_example",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "plugin3_test",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("example_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["example_id"],
            ["plugin3_example.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("plugin3_test")
    op.drop_table("plugin3_example")
    # ### end Alembic commands ###
